language: "php"

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0 
  - hhvm

before_script: 
- "composer require codeclimate/php-test-reporter --dev"
- "composer install"

script: 
- "phpunit --testsuite=unit --coverage-text --coverage-clover build/logs/clover.xml"

after_script:
- CODECLIMATE_REPO_TOKEN="60d1cac80c828eeb88a5b183fa4690e1cce333b58e2b87ddf0e61ac896847761" vendor/bin/test-reporter --stdout > codeclimate.json
- "sh -c 'if [ \"$TRAVIS_PHP_VERSION\" != \"hhvm\" ]; then curl -X POST -H \"Accept: application/vnd.api+json\" -H \"X-CC-Test-Reporter-Id: {cc_test_reporter_id}\" -d @codeclimate.json https://api.codeclimate.com/v1/test_reports ; fi'"
